### ISSUE TITLE
review spec for Z-OS feedback mechanism

### ISSUE THREAD

**Issue by despiegk** [zero-os/0-orchestrator#653] opened 2017-07-07 00:37 UTC
https://github.com/zero-os/0-orchestrator/blob/despiegk-specs/specs/feedback_mechanism_ays_service.md

**Comment by zaibon** [comment] 2017-07-10 08:44
duplicate of https://github.com/zero-os/0-orchestrator/issues/665

**Closed by zaibon** 2017-07-10 08:44 UTC
