### ISSUE TITLE
Move virtual machine within cluster from one host to another

### ISSUE THREAD

**Issue by FastGeert** [zero-os/0-orchestrator#559] opened 2017-06-30 14:07 UTC

**Comment by despiegk** [comment] 2017-07-10 07:50
is this sort of vmotion?

**Comment by grimpy** [comment] 2017-07-11 13:42
https://github.com/zero-os/0-orchestrator/issues/587

The above issue is to deal with `vmotion` aka live migration I dont like this vmware term

this issue is to make sure it also works properly when you move a vm in a halted state.

**Comment by Dinaamagdy** [comment] 2017-07-24 09:56
same as  https://github.com/zero-os/0-orchestrator/issues/215

**Comment by Dinaamagdy** [comment] 2017-07-26 14:17
can't validate due to https://github.com/zero-os/0-orchestrator/issues/215

**Comment by Dinaamagdy** [comment] 2017-08-02 10:13
duplicate of https://github.com/zero-os/0-orchestrator/issues/215

**Comment by grimpy** [comment] 2017-08-03 08:25
This is not a duplicate of #215 this issue is regarding moving a vm which is already in halted state please validate as such

**Comment by Dinaamagdy** [comment] 2017-08-03 11:39
it gives this error when I am trying to start vm again after migration 

```
Thu03 11:33] - RunStep.py          :84  :j.atyourservice.server         - INFO     - runstep 5: error
[Thu03 11:33] - Run.py              :108 :j.atyourservice.server         - ERROR    - error during execution of ste
p 5 in run a43b0d4a2a5294d2663bf1cccd5d8e44
Error of job: vm!vmtest2 (start):

Error of job: vm!vmtest2 (start):
*TRACEBACK*********************************************************************************
Traceback (most recent call last):
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/tmp/actions/vm/db8a0091678800be01d0b9ea524ba43e.py", line 671, in start
    j.tools.async.wrappers.sync(service.executeAction('install', context=job.context))
  File "/opt/code/github/jumpscale/lib9/JumpScale9Lib/tools/async/Wrappers.py", line 12, in sync
    return loop.run_until_complete(coro)
  File "/usr/lib/python3.5/asyncio/base_events.py", line 387, in run_until_complete
    return future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/lib/python3.5/asyncio/tasks.py", line 241, in _step
    result = coro.throw(exc)
  File "/opt/code/github/jumpscale/ays9/JumpScale9AYS/ays/lib/Service.py", line 683, in executeAction
    return await self.executeActionJob(action, args, context=context)
  File "/opt/code/github/jumpscale/ays9/JumpScale9AYS/ays/lib/Service.py", line 708, in executeActionJob
    result = await job.execute()
  File "/usr/lib/python3.5/asyncio/futures.py", line 361, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.5/asyncio/tasks.py", line 296, in _wakeup
    future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/tmp/actions/vm/db8a0091678800be01d0b9ea524ba43e.py", line 639, in install
    nics=nics,
  File "/usr/local/lib/python3.5/dist-packages/zeroos/core0/client/client.py", line 2050, in create
    return self._client.sync('kvm.create', args, tags=tags)
  File "/usr/local/lib/python3.5/dist-packages/zeroos/core0/client/client.py", line 716, in sync
    raise RuntimeError('invalid response: %s' % result.state, result)
RuntimeError: ('invalid response: ERROR', STATE: ERROR
STDOUT:

STDERR:

DATA:
"failed to create machine: virError(Code=1, Domain=10, Message='internal error: process exited while connecting to 
monitor: 2017-08-03T11:33:48.276468Z qemu-system-x86_64: -drive file=nbd:unix:/var/run/nbd-servers/server.socket.vm
test2:exportname=vdisk2,format=raw,if=none,id=drive-virtio-disk0,cache=none: Failed to connect socket: No such file
 or directory')"
)

```
and vm status in new node :starting 
## Software Version 
ac3e7ec3b5f2e8f09ba32b6e4889053103830a66

**Comment by Dinaamagdy** [comment] 2017-08-06 11:52
## Software Version 
7a2ef4e39ab2e7a825d2e92b35d022f3508f15e3

**Closed by Dinaamagdy** 2017-08-06 11:52 UTC
Labels: state_verification, type_feature
