### ISSUE TITLE
new "vdiskstorage" type

### ISSUE THREAD

**Issue by rkhamis** [zero-os/0-orchestrator#1051] opened 2017-09-18 09:17 UTC
Abstracts the collection of a primary block cluster, a secondary block cluster and an object cluster.

(name up for discussion)

**Comment by zaibon** [comment] 2017-09-18 10:15
duplicate of https://github.com/zero-os/0-orchestrator/issues/1055

**Closed by zaibon** 2017-09-18 10:15 UTC
Labels: process_duplicate, type_feature
